trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - 'modules/keyvault/**'

variables: 
- name: ServiceConnectionName1
  value: IaC-Publish
- name: ServiceConnectionName2
  value: IaC-Test
- name: DeploymentLocation
  value: norwayeast
- name: ResourceGroupName
  value: RG-Management
- name: ModuleName
  value: keyvault
- name: ModuleRegistryServer
  value: noeacrsiac001p.azurecr.io
- name: ModuleFilePath
  value: modules/keyvault/keyvault.bicep
- name: ModuleMetadataFilePath
  value: modules/keyvault/metadata.json
- name: DeploymentName
  value: IaC-TestDeployment-KeyVault

pool:
  vmImage: ubuntu-latest

stages:

- stage: Lint
  jobs:
  - job: LintCode
    displayName: Lint code
    steps:
      - script: |
          az bicep build --file $(ModuleFilePath)
        name: LintBicepCode
        displayName: Run Bicep linter


- stage: TestDeployment
  jobs:
  - job: DeployJob
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        connectedServiceName: $(ServiceConnectionName2)
        deploymentName: $(DeploymentName)
        location: $(DeploymentLocation)
        resourceGroupName: $(ResourceGroupName)
        csmFile: $(ModuleFilePath)
        overrideParameters: '-softdelete yes -assetowner ''mohit sharma'' -detailedPurpose ''test script test script test script test script'' -projectCode PTF -envCode test -locationCode neu -location westeurope -ownerteam Platform -criticality Low -classification Non-business -sequence 011'

- stage: Publish
  dependsOn: 
  - TestDeployment
  condition: succeeded('TestDeployment')
  jobs:
  - job: Publish
    steps:
      - script: |
          majorMinorVersionNumber=$(jq '(.version.major | tostring) + "." + (.version.minor | tostring)' $(ModuleMetadataFilePath) -r )
          versionNumber="$majorMinorVersionNumber.$(Build.BuildNumber)"
          echo "##vso[task.setvariable variable=ModuleVersion;]$versionNumber"
        name: GetModuleVersionNumber
        displayName: Get module version number
      - task: AzureCLI@2
        name: Publish
        displayName: Publish module
        inputs:
          azureSubscription: $(ServiceConnectionName1)
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az bicep publish \
              --target 'br:$(ModuleRegistryServer)/$(ModuleName):$(ModuleVersion)' \
              --file $(ModuleFilePath)